---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: lesson5
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
#  volumeName: "pv-nfs"
  storageClassName: csi-ceph-hdd-ms1
  
