---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
#    rollingUpdate:
#      maxSurge: 0
#      maxUnavailable: 1
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
#      hostNetwork: true
#      serviceAccountName: postgres
      containers:
      - image: postgres:10.13
        name: postgres
        envFrom:
#          - configMapRef:
#             name: postgres-config
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgre-secret
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: 1
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PORT
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
#        - name: conf_nginx
#          muontPath: /etc/nginx/conf.d/default.conf
        - name: pvc-nfs
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pvc-nfs
        persistentVolumeClaim:
        claimName: pvc-nfs
#      - name: conf_nginx
#        value: default.conf

