---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostNetwork: true
      serviceAccountName: postgres
      containers:
      - image: postgres:10.13
        args: ["$(POSTGRES_DB)","$(POSTGRES_USER)"]
        name: postgres
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMap:
                name: postgres-config
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMap:
                name: postgres-config
                key: POSTGRES_USER
        ports:
        - containerPort: 5432
          protocol: TCP
