---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostNetwork: true
      serviceAccountName: postgres
      containers:
      - image: postgres:10.13
        name: postgres
        env:
          - name: POSTGRES_DB
            value: POSTGRES_DB
          - name: POSTGRES_USER
            value: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            value: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          protocol: TCP
