---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: lesson5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
#  strategy:
#    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10.13
        name: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgre-secret
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: PGDATA
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: pgdata
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: pvc-nfs
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "testuser" -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
#      volumes:
#      - name: pvc-nfs
#        persistentVolumeClaim:
#          claimName: pvc-nfs
  volumeClaimTemplates:
  - metadata:
      name: pvc-nfs
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "csi-high-iops-ms1"
      resources:
        requests:
          storage: 10Gi
